[project]
name = "gent-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "contextily>=1.6.2",
    "geopandas>=1.1.0",
    "mesa>=3.2.0",
    "networkx>=3.5",
    "pip>=25.1.1",
    "shapely>=2.1.1",
]
